### ISSUE TITLE
思源最近支持了数据库，能否利用数据库来标记feed

### ISSUE THREAD

**Issue by SenLief** [2234839/feed_siyuan_plugin#3]
现在的方案比较分散，不好管理。不知道能否做到如下的实现

feed 数据表，属性类似于
| 主键 | rss url | cron | count | 
|--------|--------|--------|--------|
| Cell | Cell | Cell | Cell |
| Cell | Cell | Cell | Cell |

类似于上面的表，主键作为名称可以新建一个订阅的文档

**Comment by 2234839** [comment]
感谢反馈，我将在下一个版本实现此特性，但插件不应该主动创建该 feed 数据表
而是在 feed 块上添加对应的数据库属性，用户可自行创建相应的数据变。
然后在文档中显式声明的优先于数据库属性

**Comment by SenLief** [comment]
> 感谢反馈，我将在下一个版本实现此特性，但插件不应该主动创建该 feed 数据表 而是在 feed 块上添加对应的数据库属性，用户可自行创建相应的数据变。 然后在文档中显式声明的优先于数据库属性

我也是这个意思，上面的图只是原型图，可以类似于这种的图，这样我觉得好些，便于管理和统计。

**Comment by 2234839** [comment]
关联文档：https://ld246.com/article/1705409056161
