### ISSUE TITLE
配置问题

### ISSUE THREAD

**Issue by loonghfut** [2234839/feed_siyuan_plugin#5]
按照整个配置
![tmpA9DE](https://github.com/user-attachments/assets/9a5e8661-155b-4610-928d-f88ebe2a6b96)

为何达不到预期效果
![tmpBCCD](https://github.com/user-attachments/assets/e7635f03-5d73-4931-81a8-d8bf61cec0e0)
![tmpC29A](https://github.com/user-attachments/assets/932845f1-0a5f-4ca0-9dfc-591116c3862c)

**Comment by 2234839** [comment]
在feed: 后面加上链接试试

**Comment by loonghfut** [comment]
![tmp4BA3](https://github.com/user-attachments/assets/436c9bda-1a67-4d3b-9d49-7b41e632e6a7)
加上链接后会报错

**Comment by loonghfut** [comment]
我感觉这个配置没有起到作用
![tmp8BA6](https://github.com/user-attachments/assets/691cbbe0-2efa-4f93-b486-ec5829623bb5)

**Comment by 2234839** [comment]
![图片](https://github.com/user-attachments/assets/bdae9581-3416-49ec-a319-7c05d901c476)
你把这两个对象展开我看看

**Comment by loonghfut** [comment]
![tmp3F77](https://github.com/user-attachments/assets/e6bebbe9-d2c5-4fbc-8009-3469c20c77f6)

**Comment by 2234839** [comment]
![图片](https://github.com/user-attachments/assets/6c950274-c1fd-4d8f-8bbf-cde80edbc51f)
确实没有读取到feed属性，你那里只读取了一个 blog 属性

**Comment by 2234839** [comment]
我尝试了一下，可能是后来插件更新出了问题，等我修复一下

**Comment by loonghfut** [comment]
感谢🙏

**Comment by 2234839** [comment]
安装 v1.1.17  版就应该好了，思源改了表内字段的生成方式导致的

**Comment by 2234839** [comment]
更新后 ld246 的那个rss应该读取到的rss条目数为0，因为现在 ld246 需要登录才能访问了
